Created an interactive option. Unfortunately, it does not work because of a bug in 2.7.2! You can use it with 2.7.1, however.

diff --git a/bin/sake b/bin/sake
--- a/bin/sake
+++ b/bin/sake
@@ -4,6 +4,8 @@
 # Run "sake -h" for help.
 #===================================================================
 
+set +x
+
 if [ "$SAKE_HOME" = "" ] ; then
     SAKE_HOME=${0%bin/sake}
     if [ "$SAKE_HOME" = "" ] ; then
@@ -16,8 +18,17 @@ if [ "$SAKE_HOME" = "" ] ; then
 fi
 CLASSPATH=${SAKE_HOME}/lib/specs-1.4.1.jar:${SAKE_HOME}/lib/junit-4.4.jar:${SAKE_HOME}/lib/sake.jar:$CLASSPATH
 
-set +x
+cygwin=false;
+case "`uname`" in
+    CYGWIN*) 
+        cygwin=true 
+        SAKE_HOME=`cygpath --$format "$SAKE_HOME"`
+        CLASSPATH=`cygpath --path --$format "$CLASSPATH"`
+        ;;
+esac
+
 file=sake.scala
+interactive="false"
 args[0]=-cp
 args[1]=$CLASSPATH
 
@@ -25,20 +36,27 @@ function showhelp {
     cat <<-EOF
 usage: sake [-h] [-f sake.scala] [scala_opts] [targets]
 where:
-    -h              => this help message (also "--h", "-help", and "--help" allowed)
-    -f sake.scala   => "sake.scala" is the default build file name.
-    scala_opts      => any other options are passed to the "scala" command.
-                       Note that -cp and -classpath items will be prepended to the CLASSPATH.
-    targets         => what to build; defaults to "all"
+    -h              => This help message (also "--h", "-help", "--help", etc. are allowed)
+    -i              => Interactive mode. After loading the build file, it puts you at the scala
+                       command prompt. Use commands like "build('all)" to build targets.
+    -f build_file   => The build file name, where "sake.scala" is the default.
+    scala_opts      => Any other options are passed to the "scala" command. However, any
+                       -cp and -classpath items will be prepended to the CLASSPATH.
+    targets         => What to build; defaults to "all", unless in interactive mode, in which
+                       case nothing is built by default. If targets are specified, they are
+                       built after loading the build file and before presenting the scala prompt.
 EOF
 }
 
 while [ $# -gt 0 ]
 do
 	case $1 in
-		-h|--h|-help|--help)
+		-h*|--h*)
 			showhelp
 			exit 0
+			;;
+		-i)
+			interactive="true"
 			;;
 		-f)
 			shift
@@ -60,11 +78,28 @@ do
 	shift
 done
 
-if [ "${#targets[@]}" == 0 ]; then
-    targets[0]="all"
+if [ $interactive = "false" ]; then
+    if [ "${#targets[@]}" == 0 ]; then
+        targets[0]="all"
+    fi
+else
+    scala -version | grep --silent 2.7.2
+    if [ $? = 0 ] ; then
+        echo "The interactive option can't be used with scala v2.7.2, because a bug in"
+        echo "the -i option causes it to load the build file twice. Use v2.7.1 instead."
+        exit 1
+    fi
 fi
 
-scala ${args[@]} <<-EOF
+function stdinput {
+cat <<-EOF
 :load $file
 build("${targets[@]}")
 EOF
+}
+
+if [ $interactive = "true" ]; then
+    scala ${args[@]} -i $file
+else
+    stdinput | scala ${args[@]}
+fi
